version: "3.4"
services:
  centos8libmodsecbase:
    build:
      context: .
      dockerfile: Dockerfile.8-base
    image: rpmbuild:8-libmodsecbase
  centos7libmodsecbase:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: rpmbuild:7-libmodsecbase
  centos8libmodsec:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
  centos7libmodsec:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
