version: "3.4"
services:
  centos6libmodsecbase:
    build:
      context: .
      dockerfile: Dockerfile.6-base
    image: rpmbuild:6-libmodsecbase
  centos7libmodsecbase:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: rpmbuild:7-libmodsecbase
  centos6libmodsec:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el6
  centos7libmodsec:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
