FROM aursu/rpmbuild:6-build

USER root
RUN yum -y install \
        GeoIP-devel \
        libcurl-devel \
        libxml2-devel \
        lmdb-devel \
        pcre-devel \
        ssdeep-devel \
        yajl-devel \
    && yum clean all && rm -rf /var/cache/yum